export {default as Header} from './Header'
export {default as Menu} from './Menu'
export {default as Footer} from './Footer'
export {default as PizzaBlock} from './PizzaBlock'
export {default as HeaderWOcart} from './HeaderWOcart'
export {default as Order} from './Order'
export {default as EmptyCart} from './EmptyCart'